services:
  duckdb:
    build: .
    restart: unless-stopped
    environment:
      DUCKDB_API_KEY: ${DUCKDB_API_KEY}
      DUCKDB_FILE: /data/ellen_yt.duckdb
      DUCKDB_HTTP_PORT: ${DUCKDB_HTTP_PORT:-9999}
    volumes:
      - ./data:/data
    ports:
      - '${TAILSCALE_IP}:${DUCKDB_HTTP_PORT:-9999}:${DUCKDB_HTTP_PORT:-9999}'
    networks:
      - server-network

networks:
  server-network:
    external: true
